export const DEFAULT_SETTINGS = {
  PURPOSE: {
    TAG_EXISTING_BUSINESS: "EXISTING_BUSINESS",
    TAG_NEW_BUSINESS: "NEW_BUSINESS",
    TAG_ZIARAT: "ZIARAT",
    TAG_SCHOOL_UNI_FEES: "SCHOOL_UNI_FEES",
    TAG_PROPERTY_PURCHASE: "PROPERTY_PURCHASE",
    TAG_CAR_MOTORCYCLE: "CAR_MOTORCYCLE",
    TAG_JAMAAT_WAJEBAAT_FMB_DUES: "JAMAAT_WAJEBAAT_FMB_DUES"
  },
  AMOUNT: 1000000,
  SOURCE_OF_INCOME: {
    TAG_BUSINESS_SOLE_PROP: "BUSINESS_SOLE_PROP",
    TAG_BUSINESS_PARTNERSHIP: "BUSINESS_PARTNERSHIP",
    TAG_JOB: "JOB",
    TAG_HOME_BASED_INCOME_TUITION: "HOME_BASED_INCOME_TUITION"
  }
}
