export const RESET_STORE = 'RESET_STORE'


export const REQ_EMAIL_STATUS_UPDATE = 'REQ_EMAIL_STATUS_UPDATE'
export const REQ_EMAIL_STATUS_NOT_SENT = 'REQ_EMAIL_STATUS_NOT_SENT'
export const REQ_EMAIL_STATUS_IN_PROCESS = 'REQ_EMAIL_STATUS_IN_PROCESS'
export const REQ_EMAIL_STATUS_SENT = 'REQ_EMAIL_STATUS_SENT'
export const REQ_EMAIL_STATUS_FAILED = 'REQ_EMAIL_STATUS_FAILED'


export const SAVE_CONTACT_INFO = 'SAVE_CONTACT_INFO';
export const CAT_CONTACT_ID = 'CAT_CONTACT_ID';



export const CAT_DOORS_ID = 'CAT_DOORS_ID';
export const CAT_DOORS_TITLE = 'Metal / Steel Door';
export const CAT_DOORS_SUBTITLE = '(Single Doors, Double Doors, Multiple Locking options and accessories)';
export const OPT_SINGLE_DOOR_ID = 'OPT_SINGLE_DOOR_ID';
export const OPT_SINGLE_DOOR_HEADERTEXT = 'Single Door';
export const OPT_SINGLE_DOOR_SUBHEADERTEXT = 'Door and Frame';

export const OPT_DOUBLE_DOOR_ID = 'OPT_DOUBLE_DOOR_ID';
export const OPT_DOUBLE_DOOR_HEADERTEXT = 'Double Door';
export const OPT_DOUBLE_DOOR_SUBHEADERTEXT = 'Door and Frame';

export const CAT_TYPE_IMAGE_SELECTION = 'CAT_TYPE_IMAGE_SELECTION';
export const CAT_TYPE_CONTACT_DETAILS = 'CAT_TYPE_CONTACT_DETAILS';

//selectedOptions constants
export const SAVE_CATEGORY_OPTION = 'SAVE_CATEGORY_OPTION'

export const CAT_CONTACT_DETAILS_ID = 'CAT_CONTACT_DETAILS_ID'

export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const CREATE_REQUEST = 'CREATE_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

export const CREATE_TOPIC_REQUEST = 'CREATE_TOPIC_REQUEST';
export const CREATE_TOPIC_FAILURE = 'CREATE_TOPIC_FAILURE';
export const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS';
export const CREATE_TOPIC_DUPLICATE = 'CREATE_TOPIC_DUPLICATE';
export const GET_TOPICS = 'GET_TOPICS';
export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TOPICS_FAILURE = 'GET_TOPICS_FAILURE';
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';
export const DESTROY_TOPIC = 'DESTROY_TOPIC';
export const TYPING = 'TYPING';

export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';
